[dependencies]
ark-ff = "0.4.0"
ark-relations = "0.4.0"
ark-snark = "0.4.0"
ark-bls12-381 = "0.4.0"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }